<?php
/**
 * @category    MT
 * @package     MT_Widget
 * Copyright (C) 2008-2015 ZooExtension.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author ZooExtension.com
 * @email       magento@cleversoft.co
 */
?>
<?php if ($exist = ($block->getData('collection') && $block->getData('collection')->getSize())):?>

<?php
$productCollection  = $block->getData('collection');
$image = 'new_products_content_widget_grid';
    $type = 'widget-product-grid';

    $mode = 'grid';
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
$items =        $productCollection->getItems();
$count              = $productCollection ? $productCollection->count() : 0;
$carousel           = $block->getData('carousel');
$row                = $block->getData('row');
$column             = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $block->getData('column'));
    if($carousel != 1){
        $num = 12 / $column;
        $extClass = 'col-xs-12 col-xs-6 col-md-' . $num;
    }
?>
<div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $mode; ?>">
    <div class="block-content">
        <?php $i = 0; foreach ($items as $_item): ?>
            <?php if ($carousel == 1 && $row > 1 && $i == 0): ?>
                <div class="owl-carousel">
            <?php endif ?>
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <?php if ($i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
            <ol class="product-items <?php /* @escapeNotVerified */ echo $type; ?> <?php echo $carousel && $row == 1 ? ' owl-carousel' : '' ?>">
        <?php endif ?>

            <?php $i++ ?>
            <?php /* @escapeNotVerified */
                if($carousel == 1) echo ($i == 1) ? '<li>' : '</li><li>';
                else echo ($i == 1) ? '<li class="'. $extClass .'">' : '</li><li class="' . $extClass .'">';
            ?>
            <div class="product-item-info">
            <div class="inner-product-item-info">
                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                    <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                </a>
                <div class="product-item-details">
                    <strong class="product-item-name">
                        <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                           href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                           class="product-item-link">
                            <?php echo $block->escapeHtml($_item->getName()) ?>
                        </a>
                    </strong>
                    <?php
                    echo $block->getProductPriceHtml($_item,  \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE);
                    ?>

                    <?php if ($templateType): ?>
                        <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                    <?php endif; ?>

                    <?php if ($showWishlist || $showCompare || $showCart): ?>
                        <div class="product-item-actions">
                            <?php if ($showCart): ?>
                                <div class="actions-primary">
                                    <?php if ($_item->isSaleable()): ?>
                                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                            <button class="action tocart primary"
                                                    data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                    type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        <?php else: ?>
                                            <?php
                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                            ?>
                                            <button class="action tocart primary"
                                                    data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                    type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php if ($_item->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                            <?php if ($showWishlist || $showCompare): ?>
                                <div class="actions-secondary" data-role="add-to-links">
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                        <a href="#"
                                           data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                           class="action towishlist" data-action="add-to-wishlist"
                                           title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                        </a>
                                    <?php endif; ?>
                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                        <a href="#" class="action tocompare"
                                           data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                           title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                        </a>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>
                </div>
                </div>
            </div>
            <?php echo($i == count($items)) ? '</li>' : '' ?>
            <?php if ($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
            </ol>
            </div>
        <?php endif ?>
            <?php if ($carousel == 1 && $row > 1 && $i == $count): ?>
                </div>
            <?php endif ?>
        <?php endforeach ?>
    </div>
</div>
<?php endif ?>