<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="product-options-bottom">
    <?php echo $block->getChildHtml('', true);?>
</div>
<?php 
   $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
   $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
   echo $category->getParentCategory()->getName();
    
    echo $category->getId();
    echo $category->getName(); 
?>
