<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
$item = array_shift($filterItems);
?>
<ol class="items">
    <li>
        <div id="mt_layer_filter"
             data-template="<?=$item['template']?>"
             data-step="<?=$item['step']?>"
             data-from="<?=$item['from']?>"
             data-to="<?=$item['to']?>"
             data-min="<?=$item['min']?>"
             data-count="<?=$item['count']?>"
             data-max="<?=$item['max']?>"
             data-url="<?=$block->getUrl(
                 '*/*/*',
                 [
                     '_current'=>true,
                     '_use_rewrite' => true,
                     '_query'=>[$item['requestVar']=>'slider_from-slider_to']
                 ]); ?>">

        </div>
        <div id="mt_layer_filter_display" style="text-align: center"></div>

    </li>
</ol>


