<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="block block-search">
    <div class="block block-title"><strong><?php /* @escapeNotVerified */ echo __('Search'); ?></strong></div>
    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
            <div class="field search">
                <div class="search-dropdown">
                    <span class="search-select" value="">All categories</span>
                    <ul class="search-option-list">
                        <li class="selected" value=""><span>All categories</a></span>
                            <?php echo $block->categoryListHtml(); ?>
                    </ul>
                </div>
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                </label>
                <div class="control">
                    <input type="hidden" name="cat" id="cat-search" value="" />
                    <input id="search"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                           type="text"
                           name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                           value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                           placeholder="<?php /* @escapeNotVerified */ echo __('Search for Products'); ?>"
                           class="input-text"
                           maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?php echo $block->getChildHtml() ?>
                </div>
                <div class="actions">
                    <button type="submit"
                            title="<?php echo $block->escapeHtml(__('Search')) ?>"
                            class="action search">
                        <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <script>
        require([
            "jquery",
        ],function(){
            jQuery(document).ready(function() {
                jQuery('.search-dropdown').click(function(event) {
                    jQuery(this).children('.search-option-list').toggle();
                    jQuery('.search-option-list span').click(function(){
                        var select = jQuery(this).text();
                        var vs = jQuery(this).parent("li").val();
                        jQuery('.search-option-list li').removeClass('selected');
                        jQuery(this).parent("li").addClass('selected');
                        jQuery(this).closest('.search-dropdown').children('.search-select').text(select);
                        jQuery('#cat-search').val(vs);
                    });
                });
            });
        });
    </script>
</div>
