<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @var $block \Magento\Checkout\Block\Cart
 */

if ($block->getItemsCount()) {
?>
<h2 class="title-cart"><?php echo __('<span class="active">SHOPPING CART</span> <i class="fa fa-long-arrow-right" aria-hidden="true"></i> <span>CHECKOUT DETAIL</span> <i class="fa fa-long-arrow-right" aria-hidden="true"></i> <span>ORDER COMPLETE</span>'); ?></h2>
<?php
    echo $block->getChildHtml('with-items');
} else {
    echo $block->getChildHtml('no-items');
}
?>