<?php
/**
 * @category    MT
 * @package     MT_Filter
 * @copyright   Copyright (C) 2008-2015 ZooExtension.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author ZooExtension.com
 * @email       magento@cleversoft.co
 */
?>
<?php $barColor = $this->helper('MT\Filter\Helper\Data')->getConfig('mtfilter/general/bar_color') ?>
<style type="text/css">
    #nprogress .bar {
        background: <?php echo $barColor?>;
    }
    #nprogress .spinner-icon {
        border-top-color: <?php echo $barColor?>;
        border-left-color: <?php echo $barColor?>;
    }
    #nprogress .peg {
        -webkit-box-shadow: 0 0 15px <?php echo $barColor?>, 0 0 10px <?php echo $barColor?>;
        -moz-box-shadow: 0 0 15px <?php echo $barColor?>, 0 0 10px <?php echo $barColor?>;
        -ms-box-shadow: 0 0 15px <?php echo $barColor?>, 0 0 10px <?php echo $barColor?>;
        -o-box-shadow: 0 0 15px <?php echo $barColor?>, 0 0 10px <?php echo $barColor?>;
        box-shadow: 0 0 15px <?php echo $barColor?>, 0 0 10px <?php echo $barColor?>;
    }
</style>
<script>
    require([
        "MT_Filter/js/filter",
    ], function (Filter) {
        Filter.init('mtFilter', <?php echo $this->helper('MT\Filter\Helper\Data')->getConfig()?>);
    });
</script>
