<?php
/**
 * @category    MT
 * @package     MT_Widget
 * Copyright (C) 2008-2015 ZooExtension.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author ZooExtension.com
 * @email       magento@cleversoft.co
 */
?>
<?php
$attributes = $block->getAttibuteOptions();
$id         = $block->getConfig('id');
$scroll     = $block->getConfig('scroll');
$title      = $block->getConfig('widget_title');
?>
<div class="<?php echo $block->getConfig('classes') ?>" id="<?php echo $id ?>">
    <div class="container">
        <div class="main-heading">
            <div class="heading-wrapper-title">
                <?php if ($title): ?>
                    <h3><span><?php echo $title ?></span></h3>
                <?php endif ?>
            </div>
        </div>
        <ul class="<?php echo $scroll==1 ? 'owl-carousel ' : '' ?>">
            <?php foreach ($attributes as $attribute): ?>
                <li>
                    <?php if (isset($attribute['link'])): ?>
                        <a href="<?php //echo $attribute['link'] ?>" title="<?php echo $attribute['label'] ?>">
                    <?php endif ?>
                    <?php if ($attribute['image']): ?>
                        <?php if ($scroll == 1): ?>
                            <img class="lazyOwl img-responsive" data-src="<?php echo $attribute['image'] ?>" alt="<?php echo $attribute['label'] ?>" src="<?php echo $attribute['image'] ?>" />
                        <?php else: ?>
                            <img src="<?php echo $attribute['image'] ?>" alt="<?php echo $attribute['label'] ?>" />
                        <?php endif ?>
                    <?php else: ?>
                        <span><?php echo $attribute['label'] ?></span>
                    <?php endif ?>
                    <?php if (isset($attribute['link'])): ?>
                        </a>
                    <?php endif ?>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
    <script>
        require([
            "MT_Widget/js/frontend",
            "prototype"
        ],function(MTWidget){
            new MTWidget('<?php echo $id ?>', {
                animation: <?php echo $block->getConfig('animation') ?>,
                parallax: <?php echo $block->getConfig('parallax') ?>,
                carousel: <?php echo $block->getConfig('carousel') ?>,
                carouselConfig: null,
                kenburns: <?php echo $block->getConfig('kenburns') ?>
            });
        });
    </script>
</div>
