<?php
/**
 * @category    MT
 * @package     MT_Widget
 * Copyright (C) 2008-2015 ZooExtension.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author ZooExtension.com
 * @email       magento@cleversoft.co
 */
?>
<?php
$blocks = $block->getBlocks();
$id = $block->getConfig('id');
$scroll = $block->getConfig('scroll');
$title = $block->getConfig('widget_title');
?>
<div class="<?php echo $block->getConfig('classes') ?>" id="<?php echo $id ?>">
    <div class="block mtblock-widget block-sample clearfix">
        <?php if ($title): ?>
            <div class="main-heading">
                <div class="heading-wrapper-title">
                    <h3><span><?php echo $title ?></span></h3>
                </div>
            </div>
        <?php endif ?>

        <div class="<?php echo $scroll == 1 ? 'owl-carousel ' : 'row' ?>">
            <?php foreach ($blocks as $block): ?>
                <div class="<?php echo $scroll == 1 ? 'block-content' : $block['class'] ?>">
                    <?php echo $block['content'] ?>
                </div>
            <?php endforeach ?>
        </div>
    </div>
    <script>
        require([
            "MT_Widget/js/frontend",
            "prototype"
        ], function (MTWidget) {
            jQuery(window).resize(function () {
                updatesize();
            })

            function updatesize() {
                var mediaAspect = 16 / 9;
                <?php if($this->getData('parallax_video_layout') == 'fullscreen'):?>
                var windowW = $mt(window).width();
                var windowH = $mt(window).height();

                var windowAspect = windowW / windowH;
                if (windowAspect < mediaAspect) {
                    // taller
                    jQuery('#<?php echo $id ?>')
                        .width(windowH * mediaAspect)
                        .height(windowH);
                    jQuery('#<?php echo $id ?> video')
                        .css('top', 0)
                        .css('left', -(windowH * mediaAspect - windowW) / 2)
                        .css('height', windowH);
                } else {
                    // wider
                    jQuery('#<?php echo $id ?>')
                        .width(windowW)
                        .height(windowW / mediaAspect);
                    jQuery('#<?php echo $id ?> video')
                        .css('top', -(windowW / mediaAspect - windowH) / 2)
                        .css('left', 0)
                        .css('height', windowW / mediaAspect);
                }
                <?php endif; ?>
                <?php if($this->getData('parallax_video_layout') == 'fullwidth'):?>
                var windowW = $mt(window).width();
                var windowH =  <?php echo $this->getData('parallax_video_layout_height')?>;

                var windowAspect = windowW / windowH;
                if (windowAspect < mediaAspect) {
                    // taller
                    jQuery('#<?php echo $id ?>')
                        .width(windowH * mediaAspect)
                        .height(windowH);
                    jQuery('#<?php echo $id ?> video')
                        .css('top', 0)
                        .css('left', -(windowH * mediaAspect - windowW) / 2)
                        .css('height', windowH);
                } else {
                    // wider
                    jQuery('#<?php echo $id ?>')
                        .width(windowW)
                        .height(windowH);
                    jQuery('#<?php echo $id ?> video')
                        .css('top', -(windowW / mediaAspect - windowH) / 2)
                        .css('left', 0)
                        .css('height', windowW / mediaAspect);
                }
                <?php endif; ?>
                <?php if($this->getData('parallax_video_layout') == 'custom'):?>
                var windowW = <?php echo $this->getData('parallax_video_layout_width')?>;
                var windowH =  <?php echo $this->getData('parallax_video_layout_height')?>;

                var windowAspect = windowW / windowH;
                if (windowAspect < mediaAspect) {
                    // taller
                    jQuery('#<?php echo $id ?>')
                        .width(windowH)
                        .height(windowH);
                    jQuery('#<?php echo $id ?> video')
                        .css('top', 0)
                        .css('left', -(windowH * mediaAspect - windowW) / 2)
                        .css('height', windowH);
                } else {
                    // wider
                    jQuery('#<?php echo $id ?>')
                        .width(windowW)
                        .height(windowH);
                    jQuery('#<?php echo $id ?> video')
                        .css('top', -(windowW / mediaAspect - windowH) / 2)
                        .css('left', 0)
                        .css('height', windowW / mediaAspect);
                }
                <?php endif; ?>


            }

            jQuery(document).ready(function () {
                updatesize();
            });

            new MTWidget('<?php echo $id ?>', {
                animation: <?php echo $this->getConfig('animation') ?>,
                parallax: <?php echo $this->getConfig('parallax') ?>,
                carousel: <?php echo $this->getConfig('carousel') ?>,
                carouselConfig: null,
                kenburns: <?php echo $this->getConfig('kenburns') ?>
            });
        });
    </script>
</div>
