<?php
/**
 * @category    MT
 * @package     MT_Widget
 * Copyright (C) 2008-2015 ZooExtension.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author ZooExtension.com
 * @email       magento@cleversoft.co
 */
?>
<?php
/* @var $this MT_Widget_Block_Widget */
$_id = $block->getConfig('id');
$_title = $block->getConfig('widget_title');
$t = microtime();
?>
<div class="<?php echo $block->getConfig('classes') ?> product-collection02" id="<?php echo $_id ?>">
    <?php if ($_title): ?>
        <div class="main-heading">
            <div class="heading-wrapper-title">
                <h3><span><?php echo $_title ?></span></h3>
            </div>
        </div>
    <?php endif ?>

    <?php echo $block->renderCollection('collection', $block->getConfig('mode'), 'widget/collection/collection_position02.phtml') ?>
</div>
<script>
    require([
        "MT_Widget/js/frontend",
        "prototype"
    ], function (MTWidget) {
        new MTWidget('<?php echo $_id ?>', {
            animation: <?php echo $block->getConfig('animation') ?>,
            parallax: <?php echo $block->getConfig('parallax') ?>,
            carousel: <?php echo $block->getConfig('carousel') ?>,
            countdown: <?php echo $block->getConfig('countdown') ?>,
            countdownConfig: {  dayText: '',
                hourText: '',
                minText: '',
                secText: '',
                daySingularText: '',
                hourSingularText: '',
                minSingularText: '',
                secSingularText: ''
            },
            countdownTemplate: '<div class="day"><span class="no">%d</span><span class="text">days</span></div><div class="hours"><span class="no">%h</span><span class="text">hours</span></div><div class="min"><span class="no">%i</span><span class="text">minutes</span></div><div class="second"><span class="no">%s</span><span class="text">seconds</span></div>',
        });
    });
</script>
<?php if($this->helper('MT\Mato\Helper\Data')->getCfg('category_grid/equal_height')): ?>
<script type="text/x-magento-init">
    {
        "#<?php echo $_id ?>": {
            "equalHeight": {
                "target": ".product-item-info"
            }
        }
    }
</script>
<?php endif;?>
