<?php
/**
 * @category    MT
 * @package     MT_Widget
 * Copyright (C) 2008-2015 ZooExtension.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author ZooExtension.com
 * @email       magento@cleversoft.co
 */
?>
<?php
/* @var $this MT_Widget_Block_Widget */
$id         = $block->getConfig('id');
$title      = $block->getConfig('widget_title');
$tabs       = $block->getTabs();

$template   = 'widget/collection/collection_tab.phtml';
$t          = microtime();
?>
<div class="<?php echo $block->getConfig('classes') ?>" id="<?php echo $id ?>">
    <div class="tabs-collection">
        <div class="main-heading">
            <div class="heading-wrapper-title">
            <?php if ($title): ?>
                <h3><span><?php echo $title ?></span></h3>
            <?php endif ?>
             </div>
         </div>
        <ul class="widget-tabs nav nav-tabs">
            <?php foreach ($tabs as $index => $tab): ?>
                <li class="<?php echo $index==0 ? 'active' : '' ?>">
                    <a href="#<?php echo $id . '-' . $tab['id'] ?>"
                        data-value="<?php echo $tab['value'] ?>"
                        data-type="<?php echo $tab['type'] ?>"
                        data-limit="<?php echo $block->getLimit() ?>"
                        data-column="<?php echo $block->getConfig('column') ?>"
                        data-row="<?php echo $block->getConfig('row') ?>"
                        data-cid="<?php echo $block->getData('category_ids') ?>"
                        data-template="<?php echo $template ?>"
                        data-carousel="<?php echo $block->getConfig('scroll') ?>">
                        <?php echo $tab['label'] ?>
                    </a>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
    <div class="widget-tab-content tab-content">
        <?php foreach ($tabs as $index => $tab): ?>
            <div id="<?php echo $id . '-' . $tab['id'] ?>" class="tab-pane<?php echo $index==0 ? ' active' : '' ?>">
                <?php if ($index > 0): ?>
                    </div>
                    <?php continue ?>
                <?php endif ?>
                <?php echo $block->renderCollection($tab['type'], $tab['value'], $template) ?>
            </div>
        <?php endforeach ?>
    </div>
<script>
    var BASE_URL = '<?php /* @escapeNotVerified */ echo $block->getUrl('*') ?>';
    var FORM_KEY = '<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>';
</script>
<script>
    require([
        "MT_Widget/js/frontend",
        "prototype"
    ],function(MTWidget){
    new MTWidget('<?php echo $id ?>', {
        animation: <?php echo $block->getConfig('animation') ?>,
        collectionUrl: '<?php echo $block->getUrl('widgetfe/collection/collection') ?>',
        spinnerClass: 'spinner',
        spinnerImg: '<?php echo $this->getViewFileUrl('MT_Widget::images/loader.gif') ?>',
        parallax: <?php echo $block->getConfig('parallax') ?>,
        carousel: <?php echo $block->getConfig('carousel') ?>,
        carouselConfig: null,
        countdown: <?php echo $block->getConfig('countdown') ?>,
        countdownConfig: null,
        kenburns: <?php echo $block->getConfig('kenburns') ?>
    });
});
</script>
</div>

<?php //Mage::log(microtime() - $t) ?>
