<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 * use Magento\Framework\Registry;
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php
$_menu = $block->renderCategoriesMenuHtml(false, false, 0, 'level-top', 'sub-wrapper', false );
$routeName = $block->getRequest()->getRouteName();
$identifier = $block->getCmsIdentifier();
?>

<nav class="navigation" role="navigation">
    <ul id="mtnav" class="megamenu" data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php if($block->getConfig('mtmato/menu/home')){?>
            <li class="level0 home level-top m-dropdown parent">
                <a href="<?php echo $this->getBaseUrl(); ?>" class="level-top "><span>Home</span></a>
            </li>
        <?php }?>
        <?php
        echo $_menu;
        if($block->getConfig('mtmato/menu/enable_custom')){
            $getidentifier = $block->getConfig('mtmato/menu/static_identifier');
            $arrayidentifier = explode(";", $getidentifier);
            foreach($arrayidentifier as $mcustom){
                $static_block = explode(':', $mcustom);
                $custom_menu = $block->getModel('Magento\Cms\Model\Block')->load($static_block[0]);
                if($static_block[1]) $class = 'menu-item-'.$static_block[1];
                if($custom_menu->getIsActive()) {
                    echo '
						<li class="level0 level-top parent custom-block '.$class.'">
							<a href="#" class="level-top">
								<span>'.$custom_menu->getTitle().'</span> <i class="fa fa-caret-down"></i>
							</a>
							<div class="sub-wrapper">'.$block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($static_block[0])->toHtml().'</div>
						</li>';
                }
            }
            $urlkey = $block->getConfig('mtmato/menu/url_key');
            $arrayUrlKey = explode(";", $urlkey);
            foreach($arrayUrlKey as $url){
                $condition = explode(':', $url);
                $page = $block->getModel('Magento\Cms\Model\Page')->load($condition[0], 'identifier');
                if(isset($condition[1])) $class = 'menu-item-'.$condition[1];
                if($page->getIsActive()) {
                    ?>
                    <li class="level0 level-top parent custom-block <?php if($routeName == 'cms' && $identifier == $page->getIdentifier()) {echo " active";}?> <?php echo $class;?>">
                        <a href="<?php echo $this->helper('Magento\Cms\Helper\Page')->getPageUrl($condition[0]);?>" class="level-top">
                            <span><?php echo $page->getTitle();?></span>
                        </a>
                    </li>
                    <?php
                }
            }
        }
        ?>
    </ul>
    <script>
        require([
            "jquery",
            "MT_Megamenu/js/jquery.lib.min"
        ],function(){
            jQuery(function(){
                jQuery(".megamenu").megamenu({
                    'animation':'<?php echo $block->getConfig('mtmato/menu/effect');?>',
                    'mm_timeout': 150
                });
            });
        });
    </script>
</nav>
