<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @see \MT\Megamenu\Block\Menu
 */
?>
<?php
$_menu = $block->renderCategoriesMenuHtml(FALSE, FALSE, 0, 'level-top', 'sub-wrapper', TRUE );
$routeName = $block->getRequest()->getRouteName();
$identifier = $block->getCmsIdentifier();

?>
<?php if($_menu): ?>
    <div class="mt-navigation-vertical block hidden-xs">
        <div class="block-title">
            <strong>
                <span class="fa fa-list"></span>
                <span><?php echo __('Categories'); ?></span>
            </strong>
        </div>
        <div class="mt-main-menu-vertical">
            <ul class="megamenu-vertical">
                <!--<?php if($block->getConfig('mtmato/menu/home')){?>
			<li class="level0 home level-top<?php if($routeName == 'cms' && $identifier == 'home') {echo " active";}?> m-dropdown parent">
				<a href="<?php echo $block->getStoreManager()->getStore()->getBaseUrl(); ?>" class="level-top"><span><?php echo __('Home'); ?></span></a>
			</li>
			<?php }?>-->
                <?php
                echo $_menu;
                ?>
            </ul>
        </div>
    </div>
    <script>
        require([
            "jquery",
            "MT_Megamenu/js/jquery.lib.min"
        ],function(){
            jQuery(function(){
                jQuery(".megamenu-vertical").vmegamenu({
                    'animation':'<?php echo $block->getConfig('mtmato/menu/menuleft_effect');?>',
                    'direction': 'vertical',
                    'mm_timeout': 50
                });
            });
        });
    </script>
<?php endif ?>
