<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="newsletter-cs">
    <h4 class="title"><span><?php echo __('Newsletter') ?></span></h4>
    <div class="content">
        <form class="form subscribe"
              novalidate
              action="<?php /* @escapeNotVerified */
              echo $block->getFormActionUrl() ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-validate-detail">
            <div class="field newsletter">
                <div class="form-group label-floating">
                    <label for="i5" class=" control-label" for="newsletter"><?php /* @escapeNotVerified */
                            echo __('Your email address') ?></label>
                    <input name="email" type="email" id="newsletter" class="form-control" id="i5" 
                           data-validate="{required:true, 'validate-email':true}"/> 
                  </div>
            </div>
            <div class="actions">
                <button class="waves-effect waves-red  btn-raised action subscribe "
                         type="submit">
                 <?php /* @escapeNotVerified */
                        echo __('Subscribe') ?>
                </button>
            </div>
        </form>
    </div>
</div>

              
           