<?php
$theme = $this->helper('MT\Mato\Helper\Data');
$_prev = $theme->getPreviousProduct();
$_next = $theme->getNextProduct();
$_imageHelper = $this->helper('MT\Mato\Helper\Image');
?>
<?php if($_prev || $_next): ?>
<div class="product-prev-next nav-wrapper col-lg-3 pull-right">
    <ul>
        <?php if($_prev): ?>
            <li data-mage-init='{"hoverPrevNext":{}}' class=""><a rel="prev" class="product-prev flex-prev left" title="<?php echo $block->escapeHtml($_prev->getName()); ?>" href="<?php echo $_prev->getProductUrl(); ?>"><i class="fa fa-caret-left" aria-hidden="true"></i></a>
                <div class="nav-dropdown" style="display: none;">
                    <img id="product-collection-image-<?php echo $_prev->getId(); ?>"
                         src="<?php echo $_imageHelper->getImg($_prev, 114, 130, 'new_products_content_widget_grid'); ?>"
                         alt="<?php echo $block->stripTags($_prev->getName(), null, true) ?>" />
                </div>

            </li>
        <?php endif; ?>
        <?php if($_next): ?>
            <li data-mage-init='{"hoverPrevNext":{}}' class=""><a rel="next" class="product-next flex-next right" title="<?php echo $block->escapeHtml($_next->getName()); ?>" href="<?php echo $_next->getProductUrl(); ?>"><i class="fa fa-caret-right" aria-hidden="true"></i></a>
                <div class="nav-dropdown" style="display: none;">
                    <img id="product-collection-image-<?php echo $_next->getId(); ?>"
                     src="<?php echo $_imageHelper->getImg($_next, 114, 130, 'new_products_content_widget_grid'); ?>"
                     alt="<?php echo $block->stripTags($_next->getName(), null, true) ?>" />
                </div>
            </li>
        <?php endif; ?>
    </ul>
</div>
<?php endif; ?>
